export const locales = { pt: "pt-br", en: "en-us", es: "es-es" } as const;
export type Locale = keyof typeof locales;
export const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL || "https://frontfabi.dev";
export function localizedPath(path: string, locale: Locale) {
  return `${locale === "pt" ? "" : `/${locale}`}${path === "/" && locale !== "pt" ? "" : path}`;
}
export function parsePath(path: string[] = []) {
  const locale: Locale = path[0] === "en" || path[0] === "es" ? path[0] : "pt";
  return { locale, segments: locale === "pt" ? path : path.slice(1) };
}
export const copy = {
  pt: {
    about: "Sobre",
    blog: "Blog",
    work: "Trabalho",
    desktop: "Área de trabalho",
    welcome: "Bem-vinda ao meu cantinho da internet.",
    intro: "Pessoas, código e as coisas que aprendo pelo caminho.",
    hint: "Escolha um aplicativo para explorar.",
    settings: "Configurações",
    language: "Idioma",
    close: "Fechar janela",
    minimize: "Minimizar janela",
    maximize: "Alternar tamanho da janela",
    restore: "Restaurar janela",
    skip: "Ir para o conteúdo",
    professional: "Experiência profissional",
    community: "Comunidade & palestras",
    empty: "Ainda não há publicações neste idioma.",
    missing: "Esta página está sendo preparada.",
    back: "Voltar",
    present: "atual",
    all: "Todos",
    contact: "Vamos conversar?",
    credits: "Ícones Pixel por Streamline · CC BY 4.0",
    unavailable: "Em breve",
    home: "Início",
    archive: "Arquivo",
    posts: "Publicações",
    folders: "Pastas",
    read: "Ler publicação",
    status: "Feito de código e curiosidade.",
  },
  en: {
    about: "About",
    blog: "Blog",
    work: "Work",
    desktop: "Desktop",
    welcome: "Welcome to my corner of the internet.",
    intro: "People, code and things I learn along the way.",
    hint: "Choose an application to explore.",
    settings: "Settings",
    language: "Language",
    close: "Close window",
    minimize: "Minimize window",
    maximize: "Toggle window size",
    restore: "Restore window",
    skip: "Skip to content",
    professional: "Professional experience",
    community: "Community & talks",
    empty: "No posts in this language yet.",
    missing: "This page is being prepared.",
    back: "Back",
    present: "present",
    all: "All",
    contact: "Let’s talk?",
    credits: "Pixel icons by Streamline · CC BY 4.0",
    unavailable: "Coming soon",
    home: "Home",
    archive: "Archive",
    posts: "Posts",
    folders: "Folders",
    read: "Read post",
    status: "Made of code and curiosity.",
  },
  es: {
    about: "Sobre mí",
    blog: "Blog",
    work: "Trabajo",
    desktop: "Escritorio",
    welcome: "Bienvenida a mi rincón de internet.",
    intro: "Personas, código y lo que aprendo por el camino.",
    hint: "Elige una aplicación para explorar.",
    settings: "Configuración",
    language: "Idioma",
    close: "Cerrar ventana",
    minimize: "Minimizar ventana",
    maximize: "Cambiar tamaño de ventana",
    restore: "Restaurar ventana",
    skip: "Ir al contenido",
    professional: "Experiencia profesional",
    community: "Comunidad y charlas",
    empty: "Todavía no hay publicaciones en este idioma.",
    missing: "Esta página está en preparación.",
    back: "Volver",
    present: "actual",
    all: "Todos",
    contact: "¿Conversamos?",
    credits: "Iconos Pixel por Streamline · CC BY 4.0",
    unavailable: "Próximamente",
    home: "Inicio",
    archive: "Archivo",
    posts: "Publicaciones",
    folders: "Carpetas",
    read: "Leer publicación",
    status: "Hecho de código y curiosidad.",
  },
} as const;
